In [112]:
import inspect

# import tensorflow
import tensorflow as tf

print(tf.__version__)

2.15.0


In [113]:
# create tensor with tf.constant()
tensor = tf.constant([[1, 2, 3], [2, 5, 4]])

In [114]:
tensor  # it contain same type of elements

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 5, 4]])>

In [115]:
# dimension (ndim stands for number of dimensions)
tensor.ndim  # no of axes

2

In [116]:
tensor.shape  # (row, column)

TensorShape([2, 3])

In [117]:
type(tensor)  #  tensor datatype

tensorflow.python.framework.ops.EagerTensor

In [118]:
tensor.dtype  # elements datatype

tf.int32

In [119]:
# tensor.name

In [120]:
# martrix

matrix = tf.constant(
    [[10, 7], [3, 4], [6, 3]], dtype=tf.float16
)  # specify the data type with

matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 6.,  3.]], dtype=float16)>

In [121]:
matrix.ndim

2

In [122]:
# martrix

matrix = tf.constant(
    [[10, 7, 6], [3, 4, 4], [6, 3, 9]], dtype=tf.float16
)  # specify the data type with

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  6.],
       [ 3.,  4.,  4.],
       [ 6.,  3.,  9.]], dtype=float16)>

In [123]:
matrix.ndim

2

In [124]:
matrix = tf.constant(
    [[[1, 2, 4], [2, 3, 4]], [[1, 2, 3], [3, 2, 4]], [[5, 2, 5], [5, 3, 6]]]
)

matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 2, 4]],

       [[5, 2, 5],
        [5, 3, 6]]])>

In [125]:
matrix.ndim

3

In [126]:
tensor = tf.constant(4)

In [127]:
tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [128]:
tensor.ndim

0

In [129]:
tensor = tf.constant([3])
tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [130]:
tensor.dtype

tf.int32

In [131]:
tensor.ndim

1

In [132]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const') -> Union[tensorflow.python.framework.ops.Operation, tensorflow.python.framework.ops._EagerTensorBase]>

In [133]:
tf.Variable

tensorflow.python.ops.variables.Variable

<center style="color:white; background-color: #006a4e">tf.Variable </center>

- It's a <u style="color:#006a4e">class</u> used to create mutable tensor objects

The `tf.Variable` class in TensorFlow has several methods and attributes.

Methods:

- `assign(value)`: Assigns a new value to the variable.
- `assign_add(delta)`: Adds a value to the variable and assigns the result back to the variable.
- `assign_sub(delta)`: Subtracts a value from the variable and assigns the result back to the variable.
- `read_value()`: Returns the current value of the variable.

Attributes:

- `dtype`: The data type of the variable.
- `shape`: The shape of the variable.
- `name`: The name of the variable.
- `device`: The device on which this variable will be placed.

<center style="color:white; background-color: #006a4e">tf.Constant </center>

- It's a <u style = "color:#006a4e">function</u> used to create immutable tensor objects (constants).


In [134]:
changeable_tensor = tf.Variable([3, 4])
unchangeable_tensor = tf.constant([3, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>)

In [135]:
print(type(changeable_tensor))
print(type(unchangeable_tensor))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [136]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 4])>

<div style="color:white; background-color: #006a4e">

<b>Note:</b> Remember that the `tf.constant` function takes a tensor as an argument, not a Python value.

- Rarely in practice will you need to decide whether to use a `tf.Variable` or a `tf.constant` because TensorFlow does this for you.
- However, if you want to create a constant tensor that lives on the GPU, you need to use a `tf.constant`.

</div>


<center style="color:white; background-color: #006a4e">Random Tensor</center>


- Tensors can be created with random values by using the `tf.random` module.


<div style="color:white; background-color: #006a4e">

- The keyword `cls` refers to the class itself. It is used as a `placeholder` for the actual class name when defining class methods. This is because class methods are not bound to a specific instance of the class, but rather to the class itself. Therefore, using `cls allows the method to be called without the need to explicitly specify the class name`.

</div>


<center style="color:white; background-color: #006a4e">from_seed(cls, seed=None, **kwargs)</center>

- It has `cls` as argument because it's a `class method`. That means it can directly be called from the class itself, without the need to create an instance of the class.
- It's like an static method in C++.


In [137]:
random_1 = tf.random.Generator.from_seed(42)  # set seed for reproducibility
random_1

In [138]:
random_1 = random_1.normal(shape=(3, 2))

In [139]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [140]:
print(inspect.signature(tf.random.Generator.from_seed))

(seed, alg=None)


In [141]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [142]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [143]:
random_1 = tf.random.Generator.from_seed(42)
Random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(11)
Random_2 = random_2.normal(shape=(3, 2))

Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [144]:
Random_1 = random_1.normal(shape=(3, 2))
Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [145]:
# shuffle the order of elements in a tensor
not_shuffled = tf.constant([[10, 7], [3, 4], [2, 5]])
not_shuffled.ndim  # 2

2

- tf.random.shuffle: Randomly shuffles a tensor along its first dimension(row).


In [146]:
tf.random.set_seed(42)  # global level random seed

If we want out shuffled tensors to be same order, we've to use the global level random seed and the operation level random seed(Rule 4).

    Rule 1: If either the global seed or the operation seed is set: Both seeds are used in conjunction to determine the random sequence.

    Rule 2: If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

    Rule 3: If the global seed is set but the operation seed is not: Only the global seed is used.

    Rule 4: If the operation seed is set but the global seed is not: A default global seed and the specified operation seed are used.

Rule 4: Example

        tf.random.set_seed(10)
        tf.random.shuffle(tensor1, seed=10)
        tf.random.shuffle(tensor2, seed=10)

        # tensor1 and tensor2 will be shuffled in the same order, because both have the same global and operation seed.


In [147]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

<center style="color:white; background-color: #006a4e">Tensor From Numpy</center>


Most of the numpy operations are directly built in tensorflow.

- **tf.ones(shape, dtype=tf.float32, name=None)**, alternate of <u>np.ones(shape, dtype=np.float32)</u>
- **tf.zeros(shape, dtype=tf.float32, name=None)**, alternate of <u>np.zeros(shape, dtype=np.float32)</u>
- **tf.fill(dims, value, name=None)**, alternate of <u>np.full(dims, value, dtype=None, order='C')</u>


In [148]:
tf.ones(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [149]:
tf.zeros(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [150]:
# from numpy array to tensor
import numpy as np

numpy_A = np.arange(1, 13, dtype=np.int32)

In [151]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [152]:
rank_1_tensor = tf.constant(numpy_A, shape=(2, 6))
rank_1_tensor

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>

In [153]:
rank_2_tensor = tf.constant(numpy_A, shape=(3, 2, 2))
rank_2_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])>

In [154]:
numpy_A.resize(3, 4)

In [155]:
numpy_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [156]:
tf.Variable(numpy_A)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [157]:
print(rank_2_tensor.ndim)  # Rank of tensor
print(type(rank_2_tensor))  # type of tensor
print(rank_2_tensor.shape)  # shape of tensor
print(rank_2_tensor.dtype)  # datatype of tensor elements

3
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3, 2, 2)
<dtype: 'int32'>


In [158]:
tf.size(rank_2_tensor).numpy()

12

In [159]:
a = np.array([1, 2, 3])
b = tf.constant(a)
a[0] = 4
print(b)  # tf.Tensor([4 2 3], shape=(3,), dtype=int64)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


<center style="color:white; background-color: #006a4e">Indexing Tensor </center>


In [160]:
rank_2_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])>

In [161]:
rank_2_tensor[:2, :1, :1]

<tf.Tensor: shape=(2, 1, 1), dtype=int32, numpy=
array([[[1]],

       [[5]]])>

### tf.expand_dims(input, axis, name=None): Inserts a dimension of 1 into a tensor's shape.


In [162]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(3, 2, 2, 1), dtype=int32, numpy=
array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]]],


       [[[ 5],
         [ 6]],

        [[ 7],
         [ 8]]],


       [[[ 9],
         [10]],

        [[11],
         [12]]]])>

Manipulating tensors (tensor operations) is one of the most common and important operations in machine learning.

The most common ways to manipulate tensors are:

- `Indexing`: It's just like indexing in Python lists.
- `Expanding`: It's a way of adding dimensions to tensors. `ex: tf.expand_dims()`
- `Dimension shuffling`: It's a way of reordering the dimensions of a tensor. `ex: tf.transpose()`
- `Broadcasting`: It's a way of making tensors with different shapes compatible for element-wise operations. `ex: tf.broadcast_to()`

**Basic OPerations**
+, -, \*, /, //, \*\*, %


In [163]:
#  Multiply a matrix by itself (matrix multiplication)(column of first matrix should be equal to row of second matrix)
tf.matmul(
    rank_2_tensor, rank_2_tensor
)  # we can also use `@` operator in place of `tf.matmul` to multiply tensors together.

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[  7,  10],
        [ 15,  22]],

       [[ 67,  78],
        [ 91, 106]],

       [[191, 210],
        [231, 254]]])>

In [164]:
# Element wise multiplication
tf.multiply(rank_2_tensor, rank_2_tensor)

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[  1,   4],
        [  9,  16]],

       [[ 25,  36],
        [ 49,  64]],

       [[ 81, 100],
        [121, 144]]])>

In [165]:
tensor_1 = tf.ones(shape=(12,))

In [166]:
tensor_1

<tf.Tensor: shape=(12,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [167]:
tf.reshape(tensor_1, shape=(2, 6))

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [168]:
tf.reshape(tensor_1, shape=(3, 2, 2))

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

<center style="color:white; background-color: #006a4e">Dot Product</center>

`Matrix multiplication` is also called `dot product`.

- tf.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
- tf.tensordot(a, b, axes=2, name=None): To perform a tensor dot product along the specified axes.
- tf.einsum(equation, \*inputs, \*\*kwargs)


In [169]:
x = tf.range(1, 13, dtype=tf.int32)
x = tf.reshape(x, shape=(2, 6))


y = tf.range(12, 24, dtype=tf.int32)
y = tf.reshape(y, shape=(6, 2))

In [170]:
x, y

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])>,
 <tf.Tensor: shape=(6, 2), dtype=int32, numpy=
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])>)

In [171]:
# matrix multiplication with @ operator
x @ y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 392,  413],
       [1004, 1061]])>

In [172]:
tf.transpose(x)

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])>

In [173]:
tf.transpose(x) * y

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 12,  91],
       [ 28, 120],
       [ 48, 153],
       [ 72, 190],
       [100, 231],
       [132, 276]])>

In [174]:
x

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>

In [175]:
# matrix multiplication with tf.matmul()
tf.matmul(tf.transpose(x), tf.transpose(y))

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[103, 119, 135, 151, 167, 183],
       [128, 148, 168, 188, 208, 228],
       [153, 177, 201, 225, 249, 273],
       [178, 206, 234, 262, 290, 318],
       [203, 235, 267, 299, 331, 363],
       [228, 264, 300, 336, 372, 408]])>

In [176]:
x, y

(<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])>,
 <tf.Tensor: shape=(6, 2), dtype=int32, numpy=
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]])>)

In [177]:
# dot product
tf.tensordot(
    x, y, axes=1
)  # axes = 1 means multiply the second last dimension of x with second dimension of y
# its also called inner product

# axes = 0 means multiply the first dimension of x with first dimension of y
# its also called outer product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 392,  413],
       [1004, 1061]])>

In [178]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

c = tf.tensordot(a, b, axes=[0, 0])
print(c)

tf.Tensor(32, shape=(), dtype=int32)


In [179]:
a = tf.range(1, 13, dtype=tf.float64)
a = tf.reshape(a, shape=(2, 6))
a

<tf.Tensor: shape=(2, 6), dtype=float64, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.]])>

To change the datatype of a tensor, use the `tf.cast` function.


In [180]:
tf.cast(a, dtype=tf.int16)

<tf.Tensor: shape=(2, 6), dtype=int16, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]], dtype=int16)>

**Aggregation**


In [181]:
t = tf.range(1, -15, -1)
t

<tf.Tensor: shape=(16,), dtype=int32, numpy=
array([  1,   0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11,
       -12, -13, -14])>

In [182]:
t = tf.reshape(t, shape=(2, 8))
t

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[  1,   0,  -1,  -2,  -3,  -4,  -5,  -6],
       [ -7,  -8,  -9, -10, -11, -12, -13, -14]])>

In [183]:
abs_tensor = tf.abs(t)
abs_tensor

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[ 1,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])>

In [184]:
t

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[  1,   0,  -1,  -2,  -3,  -4,  -5,  -6],
       [ -7,  -8,  -9, -10, -11, -12, -13, -14]])>

<div style="color:white; background-color: #006a4e">
let's go through some of the most popular operations

- get the minimum
- get the maximum
- get the mean of a tensor
- get the sum of a tensor

</div>


In [185]:
tf.size(abs_tensor).numpy(), tf.shape(abs_tensor).numpy(), abs_tensor.ndim

(16, array([2, 8]), 2)

In [186]:
tf.shape(abs_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 8])>

In [187]:
abs_tensor

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[ 1,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])>

In [188]:
tf.reduce_min(abs_tensor).numpy()

0

In [189]:
tf.reduce_max(abs_tensor).numpy(), tf.reduce_mean(abs_tensor).numpy(), tf.reduce_sum(abs_tensor).numpy()

(14, 6, 106)

In [190]:
abs_tensor

<tf.Tensor: shape=(2, 8), dtype=int32, numpy=
array([[ 1,  0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13, 14]])>

<div style="color:white; background-color: #006a4e; p">
<center>
🦼variance and standard deviation
</center>
</div>

In [191]:
tf.__version__

'2.15.0'

In [192]:
# upgrade tensorflow
# %pip install --upgrade tensorflow

<div style="color:white; background-color: #006a4e">

* Real numbers refer to the number that can be either positive or negative decimal(floating-point) value.
* In TensorFlow, real number include tf.float16, tf.float32, tf.float64.
</div>

<center style="color:white; background-color: #006a4e">
🦼tf.math.reduce_variance(input_tensor, axis=None, keepdims=False, name=None)
</center>

* input_tensor: The tensor to reduce. Should be `real or complex type`.


In [193]:
tf.math.reduce_variance(tf.cast(abs_tensor, dtype=tf.float32)).numpy()


19.609375

In [194]:
tf.math.reduce_std(tf.cast(abs_tensor, dtype=tf.float32)).numpy()

4.4282475

<center style="color:white; background-color: #006a4e"> TensorFlow Probability </center>

In [195]:
# import tensorflow_probability as tfp
# tfp.stats.variance(abs_tensor)

**Positional Maximum and minimum**

In [196]:
tf.reduce_min(abs_tensor).numpy()

0

In [197]:
tf.math.argmin(abs_tensor)

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)>

In [198]:
tf.random.set_seed(42)
f = tf.random.uniform(shape= [50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [199]:
# positional maximum
tf.math.argmax(f)  # index of maximum value 
                    # tf.argmax(f) will give the index of maximum value in the tensor

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [200]:
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [201]:
assert f[tf.argmax(f)] == tf.reduce_max(f)

In [202]:
# positional minimum
tf.math.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

<center style="color:white; background-color: #006a4e">
squeezing the tensor(removing all the single dimensions)
</center>

In [203]:
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape = [50]), shape=(1, 1, 1, 1, 50))

In [204]:
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

<div style="color:white; background-color: #006a4e">

* tf.squeeze(input, axis=None, name=None, squeeze_dims=None)
* It removes all dimensions of size 1 from the input tensor along the axis specified.

</div>

In [205]:
g_tensor = tf.squeeze(g)
g_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [206]:
tf.fill([2, 3], 10), tf.eye(3), tf.linalg.diag([1, 2, 3])

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 10, 10],
        [10, 10, 10]])>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])>)

<center style="color:white; background-color: #006a4e">One hot encoding</center>

In [207]:
tensor = tf.range(1, 5)
tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [208]:
tf.one_hot(tensor, depth=4)   # depth is the number of classes in the tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [209]:
# squaring, log, square root

tensor = tf.range(1, 5, dtype=tf.float32)
tensor

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 2., 3., 4.], dtype=float32)>

**tf.squrt,tf.math.log, tf.math.exp**

* input element should be real number(positive or negative decimal value).

In [210]:
tf.square(tensor), tf.sqrt(tensor), tf.math.log(tensor)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508, 2.       ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.       , 0.6931472, 1.0986123, 1.3862944], dtype=float32)>)

<center style="color:white; background-color: #006a4e">Tensor and Numpy<center>

In [211]:
# create tensor directly from numpy array
np_array = np.arange(1, 25, dtype=np.int32)
j = tf.constant(np_array, shape=(2, 3, 4))

In [212]:
j

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [213]:
tf.constant(np.array([4, 3, 5, 6]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 3, 5, 6])>

In [214]:
np.array(j), type(np.array(j))

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]),
 numpy.ndarray)

In [215]:
tf.test.is_gpu_available(
    cuda_only=False, min_cuda_compute_capability=None
)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

Finding access to GPU

In [218]:
# tf.config.list_physical_devices('GPU')
tf.config.list_physical_devices(device_type=None)

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [219]:
!nvidia-smi

Wed Dec  6 10:40:17 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.29                 Driver Version: 531.29       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650       WDDM | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8                4W /  N/A|    571MiB /  4096MiB |     27%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

🗝️**Note**: If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.