In [1]:
import inspect
#import tensorflow
import tensorflow as tf
print(tf.__version__)


2.15.0


In [2]:
#create tensor with tf.constant()
tensor = tf.constant([[1, 2, 3], [2, 5, 4]])

In [3]:
tensor  # it contain same type of elements

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 5, 4]])>

In [4]:
# dimension (ndim stands for number of dimensions)
tensor.ndim   # no of axes

2

In [5]:
tensor.shape  #(row, column)

TensorShape([2, 3])

In [6]:
type(tensor) #  tensor datatype

tensorflow.python.framework.ops.EagerTensor

In [7]:
tensor.dtype # elements datatype

tf.int32

In [8]:
# tensor.name

In [9]:
#martrix

matrix = tf.constant([[10, 7],
                     [3, 4],
                     [6, 3]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 6.,  3.]], dtype=float16)>

In [10]:
matrix.ndim

2

In [11]:
#martrix

matrix = tf.constant([[10, 7, 6],
                     [3, 4, 4],
                     [6, 3, 9]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  6.],
       [ 3.,  4.,  4.],
       [ 6.,  3.,  9.]], dtype=float16)>

In [12]:
matrix.ndim

2

In [13]:
matrix = tf.constant([[[1, 2, 4],
                        [2, 3,4]],
                      [[1, 2, 3],
                       [3, 2, 4]],
                      [[5, 2, 5],
                       [5, 3, 6]]])
matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 2, 4]],

       [[5, 2, 5],
        [5, 3, 6]]])>

In [14]:
matrix.ndim

3

In [15]:
tensor = tf.constant(4)

In [16]:
tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [17]:
tensor.ndim

0

In [18]:
tensor = tf.constant([3])
tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [19]:
tensor.dtype

tf.int32

In [20]:
tensor.ndim

1

In [21]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const') -> Union[tensorflow.python.framework.ops.Operation, tensorflow.python.framework.ops._EagerTensorBase]>

In [22]:
tf.Variable

tensorflow.python.ops.variables.Variable

<center style="color:white; background-color: #006a4e">tf.Variable </center>

* It's a <u style="color:#006a4e">class</u> used to create mutable tensor objects 

The `tf.Variable` class in TensorFlow has several methods and attributes.

Methods:
- `assign(value)`: Assigns a new value to the variable.
- `assign_add(delta)`: Adds a value to the variable and assigns the result back to the variable.
- `assign_sub(delta)`: Subtracts a value from the variable and assigns the result back to the variable.
- `read_value()`: Returns the current value of the variable.

Attributes:
- `dtype`: The data type of the variable.
- `shape`: The shape of the variable.
- `name`: The name of the variable.
- `device`: The device on which this variable will be placed.

<center style="color:white; background-color: #006a4e">tf.Constant </center>

* It's a <u style = "color:#006a4e">function</u> used to create immutable tensor objects (constants).

In [23]:
changeable_tensor = tf.Variable([3, 4])
unchangeable_tensor = tf.constant([3, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>)

In [24]:
print(type(changeable_tensor))
print(type(unchangeable_tensor))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [25]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 4])>

<div style="color:white; background-color: #006a4e">

<b>Note:</b> Remember that the `tf.constant` function takes a tensor as an argument, not a Python value.
- Rarely in practice will you need to decide whether to use a `tf.Variable` or a `tf.constant` because TensorFlow does this for you.
- However, if you want to create a constant tensor that lives on the GPU, you need to use a `tf.constant`.

</div>

<center style="color:white; background-color: #006a4e">Random Tensor</center>

- Tensors can be created with random values by using the `tf.random` module.

<div style="color:white; background-color: #006a4e">

- The keyword `cls` refers to the class itself. It is used as a `placeholder` for the actual class name when defining class methods. This is because class methods are not bound to a specific instance of the class, but rather to the class itself. Therefore, using `cls allows the method to be called without the need to explicitly specify the class name`.

</div>

<center style="color:white; background-color: #006a4e">from_seed(cls, seed=None, **kwargs)</center>

- It has `cls` as argument because it's a `class method`. That means it can directly be called from the class itself, without the need to create an instance of the class.
- It's like an static method in C++.

In [27]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1

In [28]:
random_1 = random_1.normal(shape = (3, 2))

In [29]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [37]:
print(inspect.signature(tf.random.Generator.from_seed))

(seed, alg=None)


In [38]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [39]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [43]:
random_1 = tf.random.Generator.from_seed(42)
Random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(11)
Random_2 = random_2.normal(shape = (3, 2))

Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [44]:
Random_1 = random_1.normal(shape = (3, 2))
Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [47]:
# shuffle the order of elements in a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim # 2

2

- tf.random.shuffle: Randomly shuffles a tensor along its first dimension(row).

In [57]:
tf.random.set_seed(42) # global level random seed
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

<center style="color:white; background-color: #006a4e">Tensor From Numpy</center>

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>