In [197]:
import inspect
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [198]:
#create tensor with tf.constant()
tensor = tf.constant([[1, 2, 3], [2, 5, 4]])

In [199]:
tensor  # it contain same type of elements

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 5, 4]])>

In [200]:
# dimension (ndim stands for number of dimensions)
tensor.ndim   # no of axes

2

In [201]:
tensor.shape  #(row, column)

TensorShape([2, 3])

In [202]:
type(tensor) #  tensor datatype

tensorflow.python.framework.ops.EagerTensor

In [203]:
tensor.dtype # elements datatype

tf.int32

In [204]:
# tensor.name

In [205]:
#martrix

matrix = tf.constant([[10, 7],
                     [3, 4],
                     [6, 3]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 6.,  3.]], dtype=float16)>

In [206]:
matrix.ndim

2

In [207]:
#martrix

matrix = tf.constant([[10, 7, 6],
                     [3, 4, 4],
                     [6, 3, 9]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  6.],
       [ 3.,  4.,  4.],
       [ 6.,  3.,  9.]], dtype=float16)>

In [208]:
matrix.ndim

2

In [209]:
matrix = tf.constant([[[1, 2, 4],
                        [2, 3,4]],
                      [[1, 2, 3],
                       [3, 2, 4]],
                      [[5, 2, 5],
                       [5, 3, 6]]])
matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 2, 4]],

       [[5, 2, 5],
        [5, 3, 6]]])>

In [210]:
matrix.ndim

3

In [211]:
tensor = tf.constant(4)

In [212]:
tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [213]:
tensor.ndim

0

In [214]:
tensor = tf.constant([3])
tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [215]:
tensor.dtype

tf.int32

In [216]:
tensor.ndim

1

In [217]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const') -> Union[tensorflow.python.framework.ops.Operation, tensorflow.python.framework.ops._EagerTensorBase]>

In [218]:
tf.Variable

tensorflow.python.ops.variables.Variable

<center style="color:white; background-color: #006a4e">tf.Variable </center>

* It's a <u style="color:#006a4e">class</u> used to create mutable tensor objects 

The `tf.Variable` class in TensorFlow has several methods and attributes.

Methods:
- `assign(value)`: Assigns a new value to the variable.
- `assign_add(delta)`: Adds a value to the variable and assigns the result back to the variable.
- `assign_sub(delta)`: Subtracts a value from the variable and assigns the result back to the variable.
- `read_value()`: Returns the current value of the variable.

Attributes:
- `dtype`: The data type of the variable.
- `shape`: The shape of the variable.
- `name`: The name of the variable.
- `device`: The device on which this variable will be placed.

<center style="color:white; background-color: #006a4e">tf.Constant </center>

* It's a <u style = "color:#006a4e">function</u> used to create immutable tensor objects (constants).

In [219]:
changeable_tensor = tf.Variable([3, 4])
unchangeable_tensor = tf.constant([3, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>)

In [220]:
print(type(changeable_tensor))
print(type(unchangeable_tensor))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [221]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 4])>

<div style="color:white; background-color: #006a4e">

<b>Note:</b> Remember that the `tf.constant` function takes a tensor as an argument, not a Python value.
- Rarely in practice will you need to decide whether to use a `tf.Variable` or a `tf.constant` because TensorFlow does this for you.
- However, if you want to create a constant tensor that lives on the GPU, you need to use a `tf.constant`.

</div>

<center style="color:white; background-color: #006a4e">Random Tensor</center>

- Tensors can be created with random values by using the `tf.random` module.

<div style="color:white; background-color: #006a4e">

- The keyword `cls` refers to the class itself. It is used as a `placeholder` for the actual class name when defining class methods. This is because class methods are not bound to a specific instance of the class, but rather to the class itself. Therefore, using `cls allows the method to be called without the need to explicitly specify the class name`.

</div>

<center style="color:white; background-color: #006a4e">from_seed(cls, seed=None, **kwargs)</center>

- It has `cls` as argument because it's a `class method`. That means it can directly be called from the class itself, without the need to create an instance of the class.
- It's like an static method in C++.

In [222]:
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1

In [223]:
random_1 = random_1.normal(shape = (3, 2))

In [224]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [225]:
print(inspect.signature(tf.random.Generator.from_seed))

(seed, alg=None)


In [226]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [227]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [228]:
random_1 = tf.random.Generator.from_seed(42)
Random_1 = random_1.normal(shape = (3, 2))

random_2 = tf.random.Generator.from_seed(11)
Random_2 = random_2.normal(shape = (3, 2))

Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [229]:
Random_1 = random_1.normal(shape = (3, 2))
Random_1, Random_2, Random_1 == Random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [230]:
# shuffle the order of elements in a tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim # 2

2

- tf.random.shuffle: Randomly shuffles a tensor along its first dimension(row).

In [231]:
tf.random.set_seed(42) # global level random seed

If we want out shuffled tensors to be same order, we've to use the global level random seed and the operation level random seed(Rule 4).

    Rule 1: If either the global seed or the operation seed is set: Both seeds are used in conjunction to determine the random sequence.

    Rule 2: If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.

    Rule 3: If the global seed is set but the operation seed is not: Only the global seed is used.
    
    Rule 4: If the operation seed is set but the global seed is not: A default global seed and the specified operation seed are used.

Rule 4: Example 
    
        tf.random.set_seed(10)
        tf.random.shuffle(tensor1, seed=10)
        tf.random.shuffle(tensor2, seed=10)
        
        # tensor1 and tensor2 will be shuffled in the same order, because both have the same global and operation seed.

In [232]:
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

<center style="color:white; background-color: #006a4e">Tensor From Numpy</center>

Most of the numpy operations are directly built in tensorflow.

* **tf.ones(shape, dtype=tf.float32, name=None)**, alternate of <u>np.ones(shape, dtype=np.float32)</u>
* **tf.zeros(shape, dtype=tf.float32, name=None)**, alternate of <u>np.zeros(shape, dtype=np.float32)</u>
* **tf.fill(dims, value, name=None)**, alternate of <u>np.full(dims, value, dtype=None, order='C')</u>

In [233]:
tf.ones(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [234]:
tf.zeros(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [235]:
# from numpy array to tensor
import numpy as np

numpy_A = np.arange(1, 13, dtype = np.int32)

In [236]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [237]:
rank_1_tensor = tf.constant(numpy_A, shape = (2, 6))
rank_1_tensor

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>

In [238]:
rank_2_tensor = tf.constant(numpy_A, shape = (3, 2, 2))
rank_2_tensor

<tf.Tensor: shape=(3, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])>

In [239]:
numpy_A.resize(3, 4)

In [240]:
numpy_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [241]:
tf.Variable(numpy_A)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])>

In [242]:
print(rank_2_tensor.ndim)  # Rank of tensor
print(type(rank_2_tensor)) # type of tensor
print(rank_2_tensor.shape) # shape of tensor
print(rank_2_tensor.dtype) # datatype of tensor elements

3
<class 'tensorflow.python.framework.ops.EagerTensor'>
(3, 2, 2)
<dtype: 'int32'>


In [244]:
tf.size(rank_2_tensor).numpy()

12

In [245]:
a = np.array([1, 2, 3])
b = tf.constant(a)
a[0] = 4
print(b)  # tf.Tensor([4 2 3], shape=(3,), dtype=int64)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
