In [1]:
#import tensorflow

import tensorflow as tf
print(tf.__version__)


2.15.0


In [2]:
#create tensor with tf.constant()
tensor = tf.constant([[1, 2, 3], [2, 5, 4]])

In [3]:
tensor  # it contain same type of elements

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 5, 4]])>

In [4]:
# dimension (ndim stands for number of dimensions)
tensor.ndim   # no of axes

2

In [5]:
tensor.shape  #(row, column)

TensorShape([2, 3])

In [6]:
type(tensor) #  tensor datatype

tensorflow.python.framework.ops.EagerTensor

In [7]:
tensor.dtype # elements datatype

tf.int32

In [8]:
# tensor.name

In [9]:
#martrix

matrix = tf.constant([[10, 7],
                     [3, 4],
                     [6, 3]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 6.,  3.]], dtype=float16)>

In [10]:
matrix.ndim

2

In [11]:
#martrix

matrix = tf.constant([[10, 7, 6],
                     [3, 4, 4],
                     [6, 3, 9]], dtype = tf.float16) # specify the data type with

matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[10.,  7.,  6.],
       [ 3.,  4.,  4.],
       [ 6.,  3.,  9.]], dtype=float16)>

In [12]:
matrix.ndim

2

In [13]:
matrix = tf.constant([[[1, 2, 4],
                        [2, 3,4]],
                      [[1, 2, 3],
                       [3, 2, 4]],
                      [[5, 2, 5],
                       [5, 3, 6]]])
matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [2, 3, 4]],

       [[1, 2, 3],
        [3, 2, 4]],

       [[5, 2, 5],
        [5, 3, 6]]])>

In [14]:
matrix.ndim

3

In [15]:
tensor = tf.constant(4)

In [16]:
tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [17]:
tensor.ndim

0

In [18]:
tensor = tf.constant([3])
tensor

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3])>

In [19]:
tensor.dtype

tf.int32

In [20]:
tensor.ndim

1

In [21]:
tf.constant

<function tensorflow.python.framework.constant_op.constant(value, dtype=None, shape=None, name='Const') -> Union[tensorflow.python.framework.ops.Operation, tensorflow.python.framework.ops._EagerTensorBase]>

In [22]:
tf.Variable

tensorflow.python.ops.variables.Variable

<center style="color:white; background-color: #006a4e">tf.Variable </center>

* It's a <u style="color:#006a4e">class</u> used to create mutable tensor objects 

The `tf.Variable` class in TensorFlow has several methods and attributes.

Methods:
- `assign(value)`: Assigns a new value to the variable.
- `assign_add(delta)`: Adds a value to the variable and assigns the result back to the variable.
- `assign_sub(delta)`: Subtracts a value from the variable and assigns the result back to the variable.
- `read_value()`: Returns the current value of the variable.

Attributes:
- `dtype`: The data type of the variable.
- `shape`: The shape of the variable.
- `name`: The name of the variable.
- `device`: The device on which this variable will be placed.

<center style="color:white; background-color: #006a4e">tf.Constant </center>

* It's a <u style = "color:#006a4e">function</u> used to create immutable tensor objects (constants).

In [23]:
changeable_tensor = tf.Variable([3, 4])
unchangeable_tensor = tf.constant([3, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>)

In [24]:
print(type(changeable_tensor))
print(type(unchangeable_tensor))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [25]:
changeable_tensor[0].assign(2)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 4])>